# Autogenerated wrapper script for MUMPS_seq_jll for aarch64-apple-darwin-libgfortran5
export libcmumps, libcmumps64, libdmumps, libdmumps64, libsmumps, libsmumps64, libzmumps, libzmumps64

using CompilerSupportLibraries_jll
using METIS_jll
using OpenBLAS32_jll
using OpenBLAS_jll
JLLWrappers.@generate_wrapper_header("MUMPS_seq")
JLLWrappers.@declare_library_product(libcmumps, "@rpath/libcmumps.dylib")
JLLWrappers.@declare_library_product(libcmumps64, "@rpath/libcmumps64.dylib")
JLLWrappers.@declare_library_product(libdmumps, "@rpath/libdmumps.dylib")
JLLWrappers.@declare_library_product(libdmumps64, "@rpath/libdmumps64.dylib")
JLLWrappers.@declare_library_product(libsmumps, "@rpath/libsmumps.dylib")
JLLWrappers.@declare_library_product(libsmumps64, "@rpath/libsmumps64.dylib")
JLLWrappers.@declare_library_product(libzmumps, "@rpath/libzmumps.dylib")
JLLWrappers.@declare_library_product(libzmumps64, "@rpath/libzmumps64.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, METIS_jll, OpenBLAS32_jll, OpenBLAS_jll)
    JLLWrappers.@init_library_product(
        libcmumps,
        "lib/libcmumps.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcmumps64,
        "lib/libcmumps64.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdmumps,
        "lib/libdmumps.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdmumps64,
        "lib/libdmumps64.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsmumps,
        "lib/libsmumps.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsmumps64,
        "lib/libsmumps64.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libzmumps,
        "lib/libzmumps.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libzmumps64,
        "lib/libzmumps64.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
