# Autogenerated wrapper script for MUMPS_seq_jll for x86_64-w64-mingw32-libgfortran5
export libcmumps, libcmumps64, libdmumps, libdmumps64, libsmumps, libsmumps64, libzmumps, libzmumps64

using CompilerSupportLibraries_jll
using METIS_jll
using OpenBLAS32_jll
using OpenBLAS_jll
JLLWrappers.@generate_wrapper_header("MUMPS_seq")
JLLWrappers.@declare_library_product(libcmumps, "libcmumps.dll")
JLLWrappers.@declare_library_product(libcmumps64, "libcmumps64.dll")
JLLWrappers.@declare_library_product(libdmumps, "libdmumps.dll")
JLLWrappers.@declare_library_product(libdmumps64, "libdmumps64.dll")
JLLWrappers.@declare_library_product(libsmumps, "libsmumps.dll")
JLLWrappers.@declare_library_product(libsmumps64, "libsmumps64.dll")
JLLWrappers.@declare_library_product(libzmumps, "libzmumps.dll")
JLLWrappers.@declare_library_product(libzmumps64, "libzmumps64.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, METIS_jll, OpenBLAS32_jll, OpenBLAS_jll)
    JLLWrappers.@init_library_product(
        libcmumps,
        "bin\\libcmumps.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcmumps64,
        "bin\\libcmumps64.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdmumps,
        "bin\\libdmumps.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdmumps64,
        "bin\\libdmumps64.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsmumps,
        "bin\\libsmumps.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsmumps64,
        "bin\\libsmumps64.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libzmumps,
        "bin\\libzmumps.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libzmumps64,
        "bin\\libzmumps64.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
